// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	models "auth-service/models"

	mock "github.com/stretchr/testify/mock"
)

// RegisterRepository is an autogenerated mock type for the RegisterRepository type
type RegisterRepository struct {
	mock.Mock
}

// CreateAccount provides a mock function with given fields: account
func (_m *RegisterRepository) CreateAccount(account *models.Account) error {
	ret := _m.Called(account)

	if len(ret) == 0 {
		panic("no return value specified for CreateAccount")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Account) error); ok {
		r0 = rf(account)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewRegisterRepository creates a new instance of RegisterRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRegisterRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *RegisterRepository {
	mock := &RegisterRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
