// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v3.21.12
// source: adapter.proto

package proto_models

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendMailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	To            string                 `protobuf:"bytes,1,opt,name=to,proto3" json:"to,omitempty"`
	ToName        string                 `protobuf:"bytes,2,opt,name=to_name,json=toName,proto3" json:"to_name,omitempty"`
	Subject       string                 `protobuf:"bytes,3,opt,name=subject,proto3" json:"subject,omitempty"`
	Body          string                 `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMailRequest) Reset() {
	*x = SendMailRequest{}
	mi := &file_adapter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMailRequest) ProtoMessage() {}

func (x *SendMailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_adapter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMailRequest.ProtoReflect.Descriptor instead.
func (*SendMailRequest) Descriptor() ([]byte, []int) {
	return file_adapter_proto_rawDescGZIP(), []int{0}
}

func (x *SendMailRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *SendMailRequest) GetToName() string {
	if x != nil {
		return x.ToName
	}
	return ""
}

func (x *SendMailRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *SendMailRequest) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

type SendMailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMailResponse) Reset() {
	*x = SendMailResponse{}
	mi := &file_adapter_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMailResponse) ProtoMessage() {}

func (x *SendMailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_adapter_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMailResponse.ProtoReflect.Descriptor instead.
func (*SendMailResponse) Descriptor() ([]byte, []int) {
	return file_adapter_proto_rawDescGZIP(), []int{1}
}

func (x *SendMailResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SendLogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Level         string                 `protobuf:"bytes,2,opt,name=level,proto3" json:"level,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Metadata      string                 `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Time          string                 `protobuf:"bytes,5,opt,name=time,proto3" json:"time,omitempty"`
	Method        string                 `protobuf:"bytes,6,opt,name=method,proto3" json:"method,omitempty"`
	Path          string                 `protobuf:"bytes,7,opt,name=path,proto3" json:"path,omitempty"`
	Ip            string                 `protobuf:"bytes,8,opt,name=ip,proto3" json:"ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendLogRequest) Reset() {
	*x = SendLogRequest{}
	mi := &file_adapter_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendLogRequest) ProtoMessage() {}

func (x *SendLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_adapter_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendLogRequest.ProtoReflect.Descriptor instead.
func (*SendLogRequest) Descriptor() ([]byte, []int) {
	return file_adapter_proto_rawDescGZIP(), []int{2}
}

func (x *SendLogRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *SendLogRequest) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *SendLogRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SendLogRequest) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

func (x *SendLogRequest) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

func (x *SendLogRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *SendLogRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *SendLogRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

type SendLogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendLogResponse) Reset() {
	*x = SendLogResponse{}
	mi := &file_adapter_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendLogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendLogResponse) ProtoMessage() {}

func (x *SendLogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_adapter_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendLogResponse.ProtoReflect.Descriptor instead.
func (*SendLogResponse) Descriptor() ([]byte, []int) {
	return file_adapter_proto_rawDescGZIP(), []int{3}
}

func (x *SendLogResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_adapter_proto protoreflect.FileDescriptor

const file_adapter_proto_rawDesc = "" +
	"\n" +
	"\radapter.proto\x12\x05proto\"h\n" +
	"\x0fSendMailRequest\x12\x0e\n" +
	"\x02to\x18\x01 \x01(\tR\x02to\x12\x17\n" +
	"\ato_name\x18\x02 \x01(\tR\x06toName\x12\x18\n" +
	"\asubject\x18\x03 \x01(\tR\asubject\x12\x12\n" +
	"\x04body\x18\x04 \x01(\tR\x04body\",\n" +
	"\x10SendMailResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\xc6\x01\n" +
	"\x0eSendLogRequest\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\x12\x14\n" +
	"\x05level\x18\x02 \x01(\tR\x05level\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1a\n" +
	"\bmetadata\x18\x04 \x01(\tR\bmetadata\x12\x12\n" +
	"\x04time\x18\x05 \x01(\tR\x04time\x12\x16\n" +
	"\x06method\x18\x06 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\a \x01(\tR\x04path\x12\x0e\n" +
	"\x02ip\x18\b \x01(\tR\x02ip\"+\n" +
	"\x0fSendLogResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\x84\x01\n" +
	"\aAdapter\x12=\n" +
	"\bSendMail\x12\x16.proto.SendMailRequest\x1a\x17.proto.SendMailResponse\"\x00\x12:\n" +
	"\aSendLog\x12\x15.proto.SendLogRequest\x1a\x16.proto.SendLogResponse\"\x00B\x10Z\x0e./proto_modelsb\x06proto3"

var (
	file_adapter_proto_rawDescOnce sync.Once
	file_adapter_proto_rawDescData []byte
)

func file_adapter_proto_rawDescGZIP() []byte {
	file_adapter_proto_rawDescOnce.Do(func() {
		file_adapter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_adapter_proto_rawDesc), len(file_adapter_proto_rawDesc)))
	})
	return file_adapter_proto_rawDescData
}

var file_adapter_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_adapter_proto_goTypes = []any{
	(*SendMailRequest)(nil),  // 0: proto.SendMailRequest
	(*SendMailResponse)(nil), // 1: proto.SendMailResponse
	(*SendLogRequest)(nil),   // 2: proto.SendLogRequest
	(*SendLogResponse)(nil),  // 3: proto.SendLogResponse
}
var file_adapter_proto_depIdxs = []int32{
	0, // 0: proto.Adapter.SendMail:input_type -> proto.SendMailRequest
	2, // 1: proto.Adapter.SendLog:input_type -> proto.SendLogRequest
	1, // 2: proto.Adapter.SendMail:output_type -> proto.SendMailResponse
	3, // 3: proto.Adapter.SendLog:output_type -> proto.SendLogResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_adapter_proto_init() }
func file_adapter_proto_init() {
	if File_adapter_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_adapter_proto_rawDesc), len(file_adapter_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_adapter_proto_goTypes,
		DependencyIndexes: file_adapter_proto_depIdxs,
		MessageInfos:      file_adapter_proto_msgTypes,
	}.Build()
	File_adapter_proto = out.File
	file_adapter_proto_goTypes = nil
	file_adapter_proto_depIdxs = nil
}
