// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: user.proto

package proto_models

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterUserObj struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdCardNumber  string                 `protobuf:"bytes,1,opt,name=id_card_number,json=idCardNumber,proto3" json:"id_card_number,omitempty"`
	TitleNameTh   string                 `protobuf:"bytes,2,opt,name=title_name_th,json=titleNameTh,proto3" json:"title_name_th,omitempty"`
	FirstNameTh   string                 `protobuf:"bytes,3,opt,name=first_name_th,json=firstNameTh,proto3" json:"first_name_th,omitempty"`
	LastNameTh    string                 `protobuf:"bytes,4,opt,name=last_name_th,json=lastNameTh,proto3" json:"last_name_th,omitempty"`
	TitleNameEn   string                 `protobuf:"bytes,5,opt,name=title_name_en,json=titleNameEn,proto3" json:"title_name_en,omitempty"`
	FirstNameEn   string                 `protobuf:"bytes,6,opt,name=first_name_en,json=firstNameEn,proto3" json:"first_name_en,omitempty"`
	LastNameEn    string                 `protobuf:"bytes,7,opt,name=last_name_en,json=lastNameEn,proto3" json:"last_name_en,omitempty"`
	MobilePhone   string                 `protobuf:"bytes,8,opt,name=mobile_phone,json=mobilePhone,proto3" json:"mobile_phone,omitempty"`
	OfficePhone   string                 `protobuf:"bytes,9,opt,name=office_phone,json=officePhone,proto3" json:"office_phone,omitempty"`
	Email         string                 `protobuf:"bytes,10,opt,name=email,proto3" json:"email,omitempty"`
	Bod           string                 `protobuf:"bytes,11,opt,name=bod,proto3" json:"bod,omitempty"`
	Gender        string                 `protobuf:"bytes,12,opt,name=gender,proto3" json:"gender,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterUserObj) Reset() {
	*x = RegisterUserObj{}
	mi := &file_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterUserObj) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterUserObj) ProtoMessage() {}

func (x *RegisterUserObj) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterUserObj.ProtoReflect.Descriptor instead.
func (*RegisterUserObj) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterUserObj) GetIdCardNumber() string {
	if x != nil {
		return x.IdCardNumber
	}
	return ""
}

func (x *RegisterUserObj) GetTitleNameTh() string {
	if x != nil {
		return x.TitleNameTh
	}
	return ""
}

func (x *RegisterUserObj) GetFirstNameTh() string {
	if x != nil {
		return x.FirstNameTh
	}
	return ""
}

func (x *RegisterUserObj) GetLastNameTh() string {
	if x != nil {
		return x.LastNameTh
	}
	return ""
}

func (x *RegisterUserObj) GetTitleNameEn() string {
	if x != nil {
		return x.TitleNameEn
	}
	return ""
}

func (x *RegisterUserObj) GetFirstNameEn() string {
	if x != nil {
		return x.FirstNameEn
	}
	return ""
}

func (x *RegisterUserObj) GetLastNameEn() string {
	if x != nil {
		return x.LastNameEn
	}
	return ""
}

func (x *RegisterUserObj) GetMobilePhone() string {
	if x != nil {
		return x.MobilePhone
	}
	return ""
}

func (x *RegisterUserObj) GetOfficePhone() string {
	if x != nil {
		return x.OfficePhone
	}
	return ""
}

func (x *RegisterUserObj) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterUserObj) GetBod() string {
	if x != nil {
		return x.Bod
	}
	return ""
}

func (x *RegisterUserObj) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

type UserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RegisterUser  *RegisterUserObj       `protobuf:"bytes,2,opt,name=register_user,json=registerUser,proto3" json:"register_user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserRequest) Reset() {
	*x = UserRequest{}
	mi := &file_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRequest) ProtoMessage() {}

func (x *UserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRequest.ProtoReflect.Descriptor instead.
func (*UserRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{1}
}

func (x *UserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserRequest) GetRegisterUser() *RegisterUserObj {
	if x != nil {
		return x.RegisterUser
	}
	return nil
}

type UserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserResponse) Reset() {
	*x = UserResponse{}
	mi := &file_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserResponse) ProtoMessage() {}

func (x *UserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserResponse.ProtoReflect.Descriptor instead.
func (*UserResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{2}
}

func (x *UserResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

var File_user_proto protoreflect.FileDescriptor

const file_user_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"user.proto\x12\x05proto\"\x91\x03\n" +
	"\x0fRegisterUserObj\x12$\n" +
	"\x0eid_card_number\x18\x01 \x01(\tR\fidCardNumber\x12\"\n" +
	"\rtitle_name_th\x18\x02 \x01(\tR\vtitleNameTh\x12\"\n" +
	"\rfirst_name_th\x18\x03 \x01(\tR\vfirstNameTh\x12 \n" +
	"\flast_name_th\x18\x04 \x01(\tR\n" +
	"lastNameTh\x12\"\n" +
	"\rtitle_name_en\x18\x05 \x01(\tR\vtitleNameEn\x12\"\n" +
	"\rfirst_name_en\x18\x06 \x01(\tR\vfirstNameEn\x12 \n" +
	"\flast_name_en\x18\a \x01(\tR\n" +
	"lastNameEn\x12!\n" +
	"\fmobile_phone\x18\b \x01(\tR\vmobilePhone\x12!\n" +
	"\foffice_phone\x18\t \x01(\tR\vofficePhone\x12\x14\n" +
	"\x05email\x18\n" +
	" \x01(\tR\x05email\x12\x10\n" +
	"\x03bod\x18\v \x01(\tR\x03bod\x12\x16\n" +
	"\x06gender\x18\f \x01(\tR\x06gender\"c\n" +
	"\vUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12;\n" +
	"\rregister_user\x18\x02 \x01(\v2\x16.proto.RegisterUserObjR\fregisterUser\"'\n" +
	"\fuserResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId2A\n" +
	"\x04User\x129\n" +
	"\fRegisterUser\x12\x12.proto.UserRequest\x1a\x13.proto.userResponse\"\x00B\x10Z\x0e./proto_modelsb\x06proto3"

var (
	file_user_proto_rawDescOnce sync.Once
	file_user_proto_rawDescData []byte
)

func file_user_proto_rawDescGZIP() []byte {
	file_user_proto_rawDescOnce.Do(func() {
		file_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)))
	})
	return file_user_proto_rawDescData
}

var file_user_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_user_proto_goTypes = []any{
	(*RegisterUserObj)(nil), // 0: proto.RegisterUserObj
	(*UserRequest)(nil),     // 1: proto.UserRequest
	(*UserResponse)(nil),    // 2: proto.userResponse
}
var file_user_proto_depIdxs = []int32{
	0, // 0: proto.UserRequest.register_user:type_name -> proto.RegisterUserObj
	1, // 1: proto.User.RegisterUser:input_type -> proto.UserRequest
	2, // 2: proto.User.RegisterUser:output_type -> proto.userResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_user_proto_init() }
func file_user_proto_init() {
	if File_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_proto_goTypes,
		DependencyIndexes: file_user_proto_depIdxs,
		MessageInfos:      file_user_proto_msgTypes,
	}.Build()
	File_user_proto = out.File
	file_user_proto_goTypes = nil
	file_user_proto_depIdxs = nil
}
